server:
  port: 8080
spring:
  application:
    name:  yj-index
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.16.146:3306/lc?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true
    username: ts
    password: Ts-123456
  jooq:
    sql-dialect: mysql
  security:
    oauth2:
      client:
        provider:
          customer:
            authorization-uri: http://cloud-id.kailuan.com.cn/oauth2.0/authorize
            token-uri: http://cloud-id.kailuan.com.cn/oauth2.0/token
            user-info-uri: http://cloud-id.kailuan.com.cn/oauth2.0/user-info
            user-info-authentication-method: header
            user-name-attrivute: name
        registration:
          app:
            client-id: f8abee75-ca6b-42da-92f4-aed5101947b3
            client-secret: 8f80c265-03b1-4268-80df-90fba1a4b6c8
            client-name: app
            provider: customer
            scope: user
            redirect-uri: http://localhost:8080/test/test
            client-authentication-method: basic
            authorization-grant-type: authorization_code
file-server:
  dir: D:/uploadfile

logging:
  level:
    root: info
  file:
    path: D:\log
