server:
  port: 8080
spring:
  application:
    name:  yj-index
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.62.16.146:3306/lc?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&allowMultiQueries=true
    username: ts
    password: Ts-123456
  jooq:
    sql-dialect: mysql
  security:
    oauth2:
      client:
        provider:
          customer:
            authorization-uri: https://id.inspuronline.com/oauth2.0/authorize
            token-uri: https://id.inspuronline.com/oauth2.0/token
            user-info-uri: https://id.inspuronline.com/oauth2.0/user-info
            user-info-authentication-method: header
            user-name-attrivute: name
        registration:
          app:
            client-id: 0568c540-0456-4eb0-95e9-319ebe6aaf4a
            client-secret: 91312051-6b42-4001-a17e-af2b86bc1c0a
            client-name: app
            provider: customer
            scope: user
            redirect-uri: http://116.62.16.146:8080
            client-authentication-method: basic
            authorization-grant-type: authorization_code
file-server:
  dir: D:/uploadfile

logging:
  level:
    root: info
  file:
    path: D:\log
