/*
 * This file is generated by jOOQ.
 */
package com.cloud.kailuan.yjindex.db.tables;


import com.cloud.kailuan.yjindex.db.Keys;
import com.cloud.kailuan.yjindex.db.Lc;
import com.cloud.kailuan.yjindex.db.tables.records.LcAppInfoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * app应用模块配置
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LcAppInfo extends TableImpl<LcAppInfoRecord> {

    private static final long serialVersionUID = -1366009434;

    /**
     * The reference instance of <code>lc.lc_app_info</code>
     */
    public static final LcAppInfo LC_APP_INFO = new LcAppInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LcAppInfoRecord> getRecordType() {
        return LcAppInfoRecord.class;
    }

    /**
     * The column <code>lc.lc_app_info.id</code>.
     */
    public final TableField<LcAppInfoRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>lc.lc_app_info.app_name</code>. app名称
     */
    public final TableField<LcAppInfoRecord, String> APP_NAME = createField(DSL.name("app_name"), org.jooq.impl.SQLDataType.VARCHAR(20), this, "app名称");

    /**
     * The column <code>lc.lc_app_info.platform_type</code>. 平台类型
     */
    public final TableField<LcAppInfoRecord, String> PLATFORM_TYPE = createField(DSL.name("platform_type"), org.jooq.impl.SQLDataType.VARCHAR(20), this, "平台类型");

    /**
     * The column <code>lc.lc_app_info.app_version</code>. app版本
     */
    public final TableField<LcAppInfoRecord, String> APP_VERSION = createField(DSL.name("app_version"), org.jooq.impl.SQLDataType.VARCHAR(20), this, "app版本");

    /**
     * The column <code>lc.lc_app_info.version_info</code>. 版本说明
     */
    public final TableField<LcAppInfoRecord, String> VERSION_INFO = createField(DSL.name("version_info"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "版本说明");

    /**
     * The column <code>lc.lc_app_info.app_url</code>. app下载路径
     */
    public final TableField<LcAppInfoRecord, String> APP_URL = createField(DSL.name("app_url"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "app下载路径");

    /**
     * The column <code>lc.lc_app_info.disp_or</code>. 排序字段
     */
    public final TableField<LcAppInfoRecord, Integer> DISP_OR = createField(DSL.name("disp_or"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "排序字段");

    /**
     * The column <code>lc.lc_app_info.remark</code>. 备注
     */
    public final TableField<LcAppInfoRecord, String> REMARK = createField(DSL.name("remark"), org.jooq.impl.SQLDataType.VARCHAR(255), this, "备注");

    /**
     * The column <code>lc.lc_app_info.del_flag</code>. 逻辑删除(默认0正常，1文件已被物理删除)
     */
    public final TableField<LcAppInfoRecord, Byte> DEL_FLAG = createField(DSL.name("del_flag"), org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "逻辑删除(默认0正常，1文件已被物理删除)");

    /**
     * The column <code>lc.lc_app_info.create_by</code>. 创建人
     */
    public final TableField<LcAppInfoRecord, String> CREATE_BY = createField(DSL.name("create_by"), org.jooq.impl.SQLDataType.VARCHAR(20), this, "创建人");

    /**
     * The column <code>lc.lc_app_info.create_date</code>. 创建时间
     */
    public final TableField<LcAppInfoRecord, LocalDateTime> CREATE_DATE = createField(DSL.name("create_date"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "创建时间");

    /**
     * The column <code>lc.lc_app_info.update_by</code>. 更新人
     */
    public final TableField<LcAppInfoRecord, String> UPDATE_BY = createField(DSL.name("update_by"), org.jooq.impl.SQLDataType.VARCHAR(20), this, "更新人");

    /**
     * The column <code>lc.lc_app_info.update_date</code>. 更新时间
     */
    public final TableField<LcAppInfoRecord, LocalDateTime> UPDATE_DATE = createField(DSL.name("update_date"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "更新时间");

    /**
     * Create a <code>lc.lc_app_info</code> table reference
     */
    public LcAppInfo() {
        this(DSL.name("lc_app_info"), null);
    }

    /**
     * Create an aliased <code>lc.lc_app_info</code> table reference
     */
    public LcAppInfo(String alias) {
        this(DSL.name(alias), LC_APP_INFO);
    }

    /**
     * Create an aliased <code>lc.lc_app_info</code> table reference
     */
    public LcAppInfo(Name alias) {
        this(alias, LC_APP_INFO);
    }

    private LcAppInfo(Name alias, Table<LcAppInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private LcAppInfo(Name alias, Table<LcAppInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("app应用模块配置"), TableOptions.table());
    }

    public <O extends Record> LcAppInfo(Table<O> child, ForeignKey<O, LcAppInfoRecord> key) {
        super(child, key, LC_APP_INFO);
    }

    @Override
    public Schema getSchema() {
        return Lc.LC;
    }

    @Override
    public UniqueKey<LcAppInfoRecord> getPrimaryKey() {
        return Keys.KEY_LC_APP_INFO_PRIMARY;
    }

    @Override
    public List<UniqueKey<LcAppInfoRecord>> getKeys() {
        return Arrays.<UniqueKey<LcAppInfoRecord>>asList(Keys.KEY_LC_APP_INFO_PRIMARY);
    }

    @Override
    public TableField<LcAppInfoRecord, LocalDateTime> getRecordTimestamp() {
        return UPDATE_DATE;
    }

    @Override
    public LcAppInfo as(String alias) {
        return new LcAppInfo(DSL.name(alias), this);
    }

    @Override
    public LcAppInfo as(Name alias) {
        return new LcAppInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public LcAppInfo rename(String name) {
        return new LcAppInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LcAppInfo rename(Name name) {
        return new LcAppInfo(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, String, String, Integer, String, Byte, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
}
