/*
 * This file is generated by jOOQ.
 */
package com.cloud.kailuan.yjindex.db.tables.records;


import com.cloud.kailuan.yjindex.db.tables.LcAppInfo;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 安装包管理模块
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LcAppInfoRecord extends UpdatableRecordImpl<LcAppInfoRecord> implements Record13<Long, String, String, String, String, String, Integer, String, Byte, String, LocalDateTime, String, LocalDateTime> {

    private static final long serialVersionUID = 303560586;

    /**
     * Setter for <code>lc.lc_app_info.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lc.lc_app_info.app_name</code>. app名称
     */
    public void setAppName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.app_name</code>. app名称
     */
    public String getAppName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lc.lc_app_info.platform_type</code>. 平台类型
     */
    public void setPlatformType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.platform_type</code>. 平台类型
     */
    public String getPlatformType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lc.lc_app_info.app_version</code>. app版本
     */
    public void setAppVersion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.app_version</code>. app版本
     */
    public String getAppVersion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>lc.lc_app_info.version_info</code>. 版本说明
     */
    public void setVersionInfo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.version_info</code>. 版本说明
     */
    public String getVersionInfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>lc.lc_app_info.app_url</code>. app下载路径
     */
    public void setAppUrl(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.app_url</code>. app下载路径
     */
    public String getAppUrl() {
        return (String) get(5);
    }

    /**
     * Setter for <code>lc.lc_app_info.disp_or</code>. 排序字段
     */
    public void setDispOr(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.disp_or</code>. 排序字段
     */
    public Integer getDispOr() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>lc.lc_app_info.remark</code>. 备注
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.remark</code>. 备注
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>lc.lc_app_info.del_flag</code>. 逻辑删除(默认0正常，1文件已被物理删除)
     */
    public void setDelFlag(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.del_flag</code>. 逻辑删除(默认0正常，1文件已被物理删除)
     */
    public Byte getDelFlag() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>lc.lc_app_info.create_by</code>. 创建人
     */
    public void setCreateBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.create_by</code>. 创建人
     */
    public String getCreateBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>lc.lc_app_info.create_date</code>. 创建时间
     */
    public void setCreateDate(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.create_date</code>. 创建时间
     */
    public LocalDateTime getCreateDate() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>lc.lc_app_info.update_by</code>. 更新人
     */
    public void setUpdateBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.update_by</code>. 更新人
     */
    public String getUpdateBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>lc.lc_app_info.update_date</code>. 更新时间
     */
    public void setUpdateDate(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>lc.lc_app_info.update_date</code>. 更新时间
     */
    public LocalDateTime getUpdateDate() {
        return (LocalDateTime) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, String, String, Integer, String, Byte, String, LocalDateTime, String, LocalDateTime> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, String, String, String, Integer, String, Byte, String, LocalDateTime, String, LocalDateTime> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return LcAppInfo.LC_APP_INFO.ID;
    }

    @Override
    public Field<String> field2() {
        return LcAppInfo.LC_APP_INFO.APP_NAME;
    }

    @Override
    public Field<String> field3() {
        return LcAppInfo.LC_APP_INFO.PLATFORM_TYPE;
    }

    @Override
    public Field<String> field4() {
        return LcAppInfo.LC_APP_INFO.APP_VERSION;
    }

    @Override
    public Field<String> field5() {
        return LcAppInfo.LC_APP_INFO.VERSION_INFO;
    }

    @Override
    public Field<String> field6() {
        return LcAppInfo.LC_APP_INFO.APP_URL;
    }

    @Override
    public Field<Integer> field7() {
        return LcAppInfo.LC_APP_INFO.DISP_OR;
    }

    @Override
    public Field<String> field8() {
        return LcAppInfo.LC_APP_INFO.REMARK;
    }

    @Override
    public Field<Byte> field9() {
        return LcAppInfo.LC_APP_INFO.DEL_FLAG;
    }

    @Override
    public Field<String> field10() {
        return LcAppInfo.LC_APP_INFO.CREATE_BY;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return LcAppInfo.LC_APP_INFO.CREATE_DATE;
    }

    @Override
    public Field<String> field12() {
        return LcAppInfo.LC_APP_INFO.UPDATE_BY;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return LcAppInfo.LC_APP_INFO.UPDATE_DATE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getAppName();
    }

    @Override
    public String component3() {
        return getPlatformType();
    }

    @Override
    public String component4() {
        return getAppVersion();
    }

    @Override
    public String component5() {
        return getVersionInfo();
    }

    @Override
    public String component6() {
        return getAppUrl();
    }

    @Override
    public Integer component7() {
        return getDispOr();
    }

    @Override
    public String component8() {
        return getRemark();
    }

    @Override
    public Byte component9() {
        return getDelFlag();
    }

    @Override
    public String component10() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime component11() {
        return getCreateDate();
    }

    @Override
    public String component12() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime component13() {
        return getUpdateDate();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getAppName();
    }

    @Override
    public String value3() {
        return getPlatformType();
    }

    @Override
    public String value4() {
        return getAppVersion();
    }

    @Override
    public String value5() {
        return getVersionInfo();
    }

    @Override
    public String value6() {
        return getAppUrl();
    }

    @Override
    public Integer value7() {
        return getDispOr();
    }

    @Override
    public String value8() {
        return getRemark();
    }

    @Override
    public Byte value9() {
        return getDelFlag();
    }

    @Override
    public String value10() {
        return getCreateBy();
    }

    @Override
    public LocalDateTime value11() {
        return getCreateDate();
    }

    @Override
    public String value12() {
        return getUpdateBy();
    }

    @Override
    public LocalDateTime value13() {
        return getUpdateDate();
    }

    @Override
    public LcAppInfoRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value2(String value) {
        setAppName(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value3(String value) {
        setPlatformType(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value4(String value) {
        setAppVersion(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value5(String value) {
        setVersionInfo(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value6(String value) {
        setAppUrl(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value7(Integer value) {
        setDispOr(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value8(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value9(Byte value) {
        setDelFlag(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value10(String value) {
        setCreateBy(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value11(LocalDateTime value) {
        setCreateDate(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value12(String value) {
        setUpdateBy(value);
        return this;
    }

    @Override
    public LcAppInfoRecord value13(LocalDateTime value) {
        setUpdateDate(value);
        return this;
    }

    @Override
    public LcAppInfoRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, Integer value7, String value8, Byte value9, String value10, LocalDateTime value11, String value12, LocalDateTime value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LcAppInfoRecord
     */
    public LcAppInfoRecord() {
        super(LcAppInfo.LC_APP_INFO);
    }

    /**
     * Create a detached, initialised LcAppInfoRecord
     */
    public LcAppInfoRecord(Long id, String appName, String platformType, String appVersion, String versionInfo, String appUrl, Integer dispOr, String remark, Byte delFlag, String createBy, LocalDateTime createDate, String updateBy, LocalDateTime updateDate) {
        super(LcAppInfo.LC_APP_INFO);

        set(0, id);
        set(1, appName);
        set(2, platformType);
        set(3, appVersion);
        set(4, versionInfo);
        set(5, appUrl);
        set(6, dispOr);
        set(7, remark);
        set(8, delFlag);
        set(9, createBy);
        set(10, createDate);
        set(11, updateBy);
        set(12, updateDate);
    }
}
