/*
 * This file is generated by jOOQ.
 */
package com.cloud.kailuan.yjindex.db.tables.records;


import com.cloud.kailuan.yjindex.db.tables.LcHeaderConf;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * app头部配置
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LcHeaderConfRecord extends UpdatableRecordImpl<LcHeaderConfRecord> implements Record4<Long, String, String, String> {

    private static final long serialVersionUID = 1231175706;

    /**
     * Setter for <code>lc.lc_header_conf.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>lc.lc_header_conf.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>lc.lc_header_conf.header_name</code>. 头部名称
     */
    public void setHeaderName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>lc.lc_header_conf.header_name</code>. 头部名称
     */
    public String getHeaderName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>lc.lc_header_conf.logo_file_url</code>.
     */
    public void setLogoFileUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>lc.lc_header_conf.logo_file_url</code>.
     */
    public String getLogoFileUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>lc.lc_header_conf.bg_file_url</code>.
     */
    public void setBgFileUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>lc.lc_header_conf.bg_file_url</code>.
     */
    public String getBgFileUrl() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<Long, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return LcHeaderConf.LC_HEADER_CONF.ID;
    }

    @Override
    public Field<String> field2() {
        return LcHeaderConf.LC_HEADER_CONF.HEADER_NAME;
    }

    @Override
    public Field<String> field3() {
        return LcHeaderConf.LC_HEADER_CONF.LOGO_FILE_URL;
    }

    @Override
    public Field<String> field4() {
        return LcHeaderConf.LC_HEADER_CONF.BG_FILE_URL;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getHeaderName();
    }

    @Override
    public String component3() {
        return getLogoFileUrl();
    }

    @Override
    public String component4() {
        return getBgFileUrl();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getHeaderName();
    }

    @Override
    public String value3() {
        return getLogoFileUrl();
    }

    @Override
    public String value4() {
        return getBgFileUrl();
    }

    @Override
    public LcHeaderConfRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public LcHeaderConfRecord value2(String value) {
        setHeaderName(value);
        return this;
    }

    @Override
    public LcHeaderConfRecord value3(String value) {
        setLogoFileUrl(value);
        return this;
    }

    @Override
    public LcHeaderConfRecord value4(String value) {
        setBgFileUrl(value);
        return this;
    }

    @Override
    public LcHeaderConfRecord values(Long value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LcHeaderConfRecord
     */
    public LcHeaderConfRecord() {
        super(LcHeaderConf.LC_HEADER_CONF);
    }

    /**
     * Create a detached, initialised LcHeaderConfRecord
     */
    public LcHeaderConfRecord(Long id, String headerName, String logoFileUrl, String bgFileUrl) {
        super(LcHeaderConf.LC_HEADER_CONF);

        set(0, id);
        set(1, headerName);
        set(2, logoFileUrl);
        set(3, bgFileUrl);
    }
}
