/*
 * This file is generated by jOOQ.
 */
package com.cloud.kailuan.yjindex.db;


import com.cloud.kailuan.yjindex.db.tables.LcAppInfo;
import com.cloud.kailuan.yjindex.db.tables.LcAppModuleConf;
import com.cloud.kailuan.yjindex.db.tables.LcBootBannerConf;
import com.cloud.kailuan.yjindex.db.tables.LcHeaderConf;
import com.cloud.kailuan.yjindex.db.tables.LcHomeBannerConf;
import com.cloud.kailuan.yjindex.db.tables.LcInfoBannerConf;
import com.cloud.kailuan.yjindex.db.tables.records.LcAppInfoRecord;
import com.cloud.kailuan.yjindex.db.tables.records.LcAppModuleConfRecord;
import com.cloud.kailuan.yjindex.db.tables.records.LcBootBannerConfRecord;
import com.cloud.kailuan.yjindex.db.tables.records.LcHeaderConfRecord;
import com.cloud.kailuan.yjindex.db.tables.records.LcHomeBannerConfRecord;
import com.cloud.kailuan.yjindex.db.tables.records.LcInfoBannerConfRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>lc</code> schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<LcAppInfoRecord> KEY_LC_APP_INFO_PRIMARY = UniqueKeys0.KEY_LC_APP_INFO_PRIMARY;
    public static final UniqueKey<LcAppModuleConfRecord> KEY_LC_APP_MODULE_CONF_PRIMARY = UniqueKeys0.KEY_LC_APP_MODULE_CONF_PRIMARY;
    public static final UniqueKey<LcBootBannerConfRecord> KEY_LC_BOOT_BANNER_CONF_PRIMARY = UniqueKeys0.KEY_LC_BOOT_BANNER_CONF_PRIMARY;
    public static final UniqueKey<LcHeaderConfRecord> KEY_LC_HEADER_CONF_PRIMARY = UniqueKeys0.KEY_LC_HEADER_CONF_PRIMARY;
    public static final UniqueKey<LcHomeBannerConfRecord> KEY_LC_HOME_BANNER_CONF_PRIMARY = UniqueKeys0.KEY_LC_HOME_BANNER_CONF_PRIMARY;
    public static final UniqueKey<LcInfoBannerConfRecord> KEY_LC_INFO_BANNER_CONF_PRIMARY = UniqueKeys0.KEY_LC_INFO_BANNER_CONF_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<LcAppInfoRecord> KEY_LC_APP_INFO_PRIMARY = Internal.createUniqueKey(LcAppInfo.LC_APP_INFO, "KEY_lc_app_info_PRIMARY", new TableField[] { LcAppInfo.LC_APP_INFO.ID }, true);
        public static final UniqueKey<LcAppModuleConfRecord> KEY_LC_APP_MODULE_CONF_PRIMARY = Internal.createUniqueKey(LcAppModuleConf.LC_APP_MODULE_CONF, "KEY_lc_app_module_conf_PRIMARY", new TableField[] { LcAppModuleConf.LC_APP_MODULE_CONF.ID }, true);
        public static final UniqueKey<LcBootBannerConfRecord> KEY_LC_BOOT_BANNER_CONF_PRIMARY = Internal.createUniqueKey(LcBootBannerConf.LC_BOOT_BANNER_CONF, "KEY_lc_boot_banner_conf_PRIMARY", new TableField[] { LcBootBannerConf.LC_BOOT_BANNER_CONF.ID }, true);
        public static final UniqueKey<LcHeaderConfRecord> KEY_LC_HEADER_CONF_PRIMARY = Internal.createUniqueKey(LcHeaderConf.LC_HEADER_CONF, "KEY_lc_header_conf_PRIMARY", new TableField[] { LcHeaderConf.LC_HEADER_CONF.ID }, true);
        public static final UniqueKey<LcHomeBannerConfRecord> KEY_LC_HOME_BANNER_CONF_PRIMARY = Internal.createUniqueKey(LcHomeBannerConf.LC_HOME_BANNER_CONF, "KEY_lc_home_banner_conf_PRIMARY", new TableField[] { LcHomeBannerConf.LC_HOME_BANNER_CONF.ID }, true);
        public static final UniqueKey<LcInfoBannerConfRecord> KEY_LC_INFO_BANNER_CONF_PRIMARY = Internal.createUniqueKey(LcInfoBannerConf.LC_INFO_BANNER_CONF, "KEY_lc_info_banner_conf_PRIMARY", new TableField[] { LcInfoBannerConf.LC_INFO_BANNER_CONF.ID }, true);
    }
}
