/*
 * This file is generated by jOOQ.
 */
package com.cloud.kailuan.yjindex.db;


import com.cloud.kailuan.yjindex.db.tables.LcAppInfo;
import com.cloud.kailuan.yjindex.db.tables.LcAppModuleConf;
import com.cloud.kailuan.yjindex.db.tables.LcFileInfo;
import com.cloud.kailuan.yjindex.db.tables.LcHeaderConf;
import com.cloud.kailuan.yjindex.db.tables.LcHomeBannerConf;
import com.cloud.kailuan.yjindex.db.tables.LcInfoBannerConf;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Lc extends SchemaImpl {

    private static final long serialVersionUID = -32415691;

    /**
     * The reference instance of <code>lc</code>
     */
    public static final Lc LC = new Lc();

    /**
     * 安装包管理模块

     */
    public final LcAppInfo LC_APP_INFO = LcAppInfo.LC_APP_INFO;

    /**
     * app应用模块配置
     */
    public final LcAppModuleConf LC_APP_MODULE_CONF = LcAppModuleConf.LC_APP_MODULE_CONF;

    /**
     * The table <code>lc.lc_file_info</code>.
     */
    public final LcFileInfo LC_FILE_INFO = LcFileInfo.LC_FILE_INFO;

    /**
     * app头部配置
     */
    public final LcHeaderConf LC_HEADER_CONF = LcHeaderConf.LC_HEADER_CONF;

    /**
     * 首页banner图广告配置
     */
    public final LcHomeBannerConf LC_HOME_BANNER_CONF = LcHomeBannerConf.LC_HOME_BANNER_CONF;

    /**
     * 资讯新闻配置
     */
    public final LcInfoBannerConf LC_INFO_BANNER_CONF = LcInfoBannerConf.LC_INFO_BANNER_CONF;

    /**
     * No further instances allowed
     */
    private Lc() {
        super("lc", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            LcAppInfo.LC_APP_INFO,
            LcAppModuleConf.LC_APP_MODULE_CONF,
            LcFileInfo.LC_FILE_INFO,
            LcHeaderConf.LC_HEADER_CONF,
            LcHomeBannerConf.LC_HOME_BANNER_CONF,
            LcInfoBannerConf.LC_INFO_BANNER_CONF);
    }
}
