/*
 * This file is generated by jOOQ.
 */
package com.cloud.kailuan.yjindex.db;


import com.cloud.kailuan.yjindex.db.tables.LcAppInfo;
import com.cloud.kailuan.yjindex.db.tables.LcAppModuleConf;
import com.cloud.kailuan.yjindex.db.tables.LcFileInfo;
import com.cloud.kailuan.yjindex.db.tables.LcHeaderConf;
import com.cloud.kailuan.yjindex.db.tables.LcHomeBannerConf;
import com.cloud.kailuan.yjindex.db.tables.LcInfoBannerConf;


/**
 * Convenience access to all tables in lc
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 安装包管理模块

     */
    public static final LcAppInfo LC_APP_INFO = LcAppInfo.LC_APP_INFO;

    /**
     * app应用模块配置
     */
    public static final LcAppModuleConf LC_APP_MODULE_CONF = LcAppModuleConf.LC_APP_MODULE_CONF;

    /**
     * The table <code>lc.lc_file_info</code>.
     */
    public static final LcFileInfo LC_FILE_INFO = LcFileInfo.LC_FILE_INFO;

    /**
     * app头部配置
     */
    public static final LcHeaderConf LC_HEADER_CONF = LcHeaderConf.LC_HEADER_CONF;

    /**
     * 首页banner图广告配置
     */
    public static final LcHomeBannerConf LC_HOME_BANNER_CONF = LcHomeBannerConf.LC_HOME_BANNER_CONF;

    /**
     * 资讯新闻配置
     */
    public static final LcInfoBannerConf LC_INFO_BANNER_CONF = LcInfoBannerConf.LC_INFO_BANNER_CONF;
}
